### ISSUE TITLE
Crash on stack smashing detected

### ISSUE THREAD

**Issue by lambdabaa** [audreyt/node-webworker-threads#91] opened 2016-01-13 04:39 UTC
```
                                            hm���p:                                                 �l���{Object}
                                            �l���Symbol(record)_3.j9xtl69yxwobhuxr:                                                l���{Object}
                                           l���p:                                                 Xk���{Object}
                                            Xk���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 �j���{Object}
                                            �j���p:                                                 �i���{Object}
                                            �i���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 Hi���{Object}
                                            Hi���p:                                                 �h���{Object}
                                            �h���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 �g���{Object}
                                            �g���p:                                                 8g���{Object}
                                            8g���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 �f���{Object}
                                            �f���p:                                                 �e���{Object}
                                            �e���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 (e���{Object}
                                            (e���p:                                                 xd���{Object}
                                            xd���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 �c���{Object}
                                            �c���p:                                                 c���{Object}
                                            c���Symbol(record)_3.j9xtl69yxwobhuxr:                                                 hb���{Object}
                                            hb���p:                                                 �a���{Object}
                                            �a���Symbol(record)_3.j9xtl69yxwobhuxr:                                                a���0
```

**\* stack smashing detected ***: /home/gareth/.npm/bin/node/v3.3.1/bin/iojs terminated
Aborted (core dumped)

**Comment by gaye** [comment] 2016-01-13 05:26
This occurs on every theoretically supported version of node

**Comment by audreyt** [comment] 2016-01-13 06:49
Would you like to post the `.js` program that caused the crash?

**Comment by brodybits** [comment] 2016-11-03 18:06
Closing due to missing information. If you continue to have problems with a recent version of Node.js please feel free to post a reproduction program here or in a new issue for us to look at.

**Closed by brodybits** 2016-11-03 18:06 UTC
Labels: question
