### ISSUE TITLE
undefined symbol:node_module_register

### ISSUE THREAD

**Issue by fubh** [audreyt/node-webworker-threads#122] opened 2016-10-14 07:52 UTC
my machine is ubuntu14.04 but it can't connect innernet ,so i can't use npm command ,i cp node-webworker-threads code to my project that on my ubuntu14.04,and i start my project  it tell me  undefined symbol:node_module_register,detail error info is :
/usr/lib64/node_modules/redis/index.js:540
            throw err;
                  ^
Error: /usr/lib64/node_modules/webworker-threads/build/Release/WebWorkerThreads.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/lib64/node_modules/webworker-threads/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib64/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

could someone help me

**Comment by brodybits** [comment] 2016-11-03 18:12
Looks like a duplicate of #121, caused by an installation problem.

**Closed by brodybits** 2016-11-03 18:12 UTC
Labels: duplicate, invalid, question
